<a href="https://colab.research.google.com/github/Nokibulofficial18/NoSafenet-Python-for-AI-and-ML-/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [8]:
# code here
import numpy as np
arr = np.random.randint(101,size=3*4).reshape(3,4)
print(arr)
print()
print(np.sort(arr))
print()
print(arr[arr[:,1].argsort()])
print()
row_max = arr.max(axis=1)
sorted_idx = row_max.argsort()
print(arr[sorted_idx])
print()
print(np.sort(arr).reshape(arr.shape))

[[70  0 38 47]
 [67 95 99 64]
 [76 40 51 12]]

[[ 0 38 47 70]
 [64 67 95 99]
 [12 40 51 76]]

[[70  0 38 47]
 [76 40 51 12]
 [67 95 99 64]]

[[70  0 38 47]
 [76 40 51 12]
 [67 95 99 64]]

[[ 0 38 47 70]
 [64 67 95 99]
 [12 40 51 76]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [10]:
import numpy as np

marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)


rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
new_stu = np.vstack((rec1, rec2))


marks_update = np.hstack((marks, extra_subject))


full = np.vstack((marks_update, new_stu))


total = np.sum(full, axis=1).reshape(-1, 1)
full_with_total = np.hstack((full, total))

sorted_by_total = full_with_total[np.argsort(full_with_total[:, -1])[::-1]]


top_2 = sorted_by_total[:2]

print(top_2)


[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [11]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
uniq_row = np.unique(arr,axis=0)
print(uniq_row)
print()
uniq_col = np.unique(arr,axis=1)
print(uniq_col)

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [12]:
# code here
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [16]:
# code here
arr = np.array([
      [1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )

x = 6

row_idx = np.where(np.any(arr>x,axis=1))[0]
print(row_idx)

[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [17]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [24]:
# code here
print(np.hstack((arr1,arr2,arr3)))
print(np.concatenate((arr1,arr2,arr3)))
# print(np.ravel([arr1, arr2, arr3]))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [25]:
from typing import final
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
print()
flat_arr = arr.flatten()

min_val = flat_arr.min()
max_val = flat_arr.max()

final_arr = flat_arr[(flat_arr!=min_val)&(flat_arr!=max_val)]
print(final_arr)

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]

[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 22

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [27]:
# code here
arr = np.random.randint(100,701,size=100)
print(arr)
arr = np.clip(arr,100,200)
print()
print(arr)
arr = np.sort(arr)
print()
print(arr)
arr = np.cumsum(arr)
print()
print(arr)

[252 689 151 509 316 288 665 148 290 510 620 263 455 471 334 471 598 400
 301 529 362 508 272 663 569 299 464 556 392 189 513 547 116 142 320 193
 698 537 464 224 326 263 312 364 253 588 157 468 476 279 403 670 379 643
 371 508 312 250 176 504 301 407 655 640 286 278 316 534 327 348 243 665
 447 391 171 494 207 276 469 674 502 276 334 142 150 227 321 585 245 568
 352 625 382 279 557 327 690 522 372 107]

[200 200 151 200 200 200 200 148 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 189 200 200 116 142 200 193
 200 200 200 200 200 200 200 200 200 200 157 200 200 200 200 200 200 200
 200 200 200 200 176 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 171 200 200 200 200 200 200 200 200 142 150 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 107]

[107 116 142 142 148 150 151 157 171 176 189 193 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 2

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [28]:
# code here
np.random.seed(0)
arr = np.random.rand(1000)

arr_rounded = np.round(arr,3)
percentile_0 = np.percentile(arr_rounded, 0)
min_val = arr_rounded.min()

percentile_100 = np.percentile(arr_rounded, 100)
max_val = arr_rounded.max()


percentile_50 = np.percentile(arr_rounded, 50)
percentile_51 = np.percentile(arr_rounded, 51)
difference = percentile_51 - percentile_50


print(f"0th percentile: {percentile_0}, Minimum: {min_val}")
print(f"100th percentile: {percentile_100}, Maximum: {max_val}")
print(f"Difference between 51st and 50th percentile: {difference}")

0th percentile: 0.001, Minimum: 0.001
100th percentile: 1.0, Maximum: 1.0
Difference between 51st and 50th percentile: 0.009480000000000044
