<a href="https://colab.research.google.com/github/Nokibulofficial18/NoSafenet-Python-for-AI-and-ML-/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [4]:
#Code here
vector = np.zeros(10, dtype=int)
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
#Code here
import numpy as np
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
limit = a*b
arr = np.arange(1,limit+1).reshape(a,b)
arr

Enter the first number: 4
Enter the second number: 5


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

5###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [12]:
#Code here
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
arr=np.ones(a*b,dtype=int).reshape(a,b)
if a>2 and b>2:
  arr[1:-1,1:-1]=0

print(arr)



Enter the first number: 4
Enter the second number: 4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


55###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [17]:
#Code here
vector = np.linspace(0,1,12)[1:-1]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [20]:
#Code here
arr= np.eye(3,4, dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [21]:
#Code here
arr = np.tile(np.arange(5),(5,1))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [22]:
#code here
point = np.array([2,3])
coordinates = np.random.randint(1,101,size=(10,2))

distance = np.sqrt(np.sum((coordinates-point)**2,axis=1))

int_distance = distance.astype(int)

int_distance

array([104,  27,  38,  51,  75,  40,  76,  61, 101,  83])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [3]:
#Code here
arr = np.arange(6*7*8).reshape(6,7,8)
idx = 99
ele = arr.flatten()[idx]

idx_3d = np.unravel_index(idx,arr.shape)
print(ele,idx_3d,arr[1,5,3])

99 (np.int64(1), np.int64(5), np.int64(3)) 99


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [5]:
#Code here
input_str = input()
arr = np.array(input_str.split(), dtype=float)

reversed_arr = arr[::-1]

print(reversed_arr)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [7]:
#Code here
arr = np.array([1,2])
print(len(arr))

2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [10]:
#Code here
def softmax_function(arr):
  if not isinstance(arr,np.ndarray):
    raise ValueError("Input must be a Numpy Array")
  if arr.ndim != 1:
    raise ValueError("Input Must be a 1D Numpy Array")

  exps = np.exp(arr-np.max(arr))
  return exps / np.sum(exps)




In [11]:
input_str = input()
arr = np.array(input_str.split(), dtype=float)

print(softmax_function(arr))

86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318
[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [13]:
#Coder here


def vertical_stack(*arrays):

    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise ValueError("All inputs must be NumPy arrays.")


    return np.vstack(arrays)


In [14]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

result1 = vertical_stack(a, b)
print("Example 1 Result:\n", result1)

result2 = vertical_stack(a, b, c)
print("Example 2 Result:\n", result2)

Example 1 Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Example 2 Result:
 [[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [15]:
#Code here
import numpy as np
from datetime import datetime

def date_array(start, end):

    if not isinstance(start, str) or not isinstance(end, str):
        raise ValueError("Both start and end dates must be strings.")


    try:
        start_date = datetime.strptime(start, '%Y-%m-%d')
        end_date = datetime.strptime(end, '%Y-%m-%d')
    except ValueError:
        raise ValueError("Dates must be in 'YYYY-MM-DD' format like '2022-12-6'.")


    if start_date.year != end_date.year:
        raise ValueError("Start and end dates must be in the same year.")

    dates = np.arange(np.datetime64(start), np.datetime64(end) + 1, dtype='datetime64[D]')

    return dates.astype(str)


In [17]:
print(date_array(start='2020-09-15', end='2020-09-25'))
print(date_array(start='2022-12-01', end='2022-12-06'))
print(date_array(start='2020-11-25', end='2020-11-30'))


['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06']
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [19]:
#code here
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
result = matrix - matrix.mean(axis=1,keepdims=True)
result

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [20]:
#Code here
matrix[:,[0,1]] = matrix[:,[1,0]]
matrix

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [22]:
matrix[matrix%2==1]=-1
matrix

array([[ 2, -1, -1],
       [-1,  4,  6],
       [ 8, -1, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [23]:
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)
print(result)


[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [24]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 548, 8376, 7593, 4337, 6207],
       [2919,  696, 5872, 4857, 7442],
       [  65, 7313, 7282, 1077, 1124],
       [2388, 4459, 5302,  406, 1652],
       [ 907, 1829, 5979, 5975, 5665],
       [5288, 4368, 2726,  180, 5087],
       [5743, 8915,  992, 5640, 7289],
       [3932, 5809, 5849, 9834, 3916]])

In [26]:
#Code here
arr_normalised = (arr-arr.min())/(arr.max()-arr.min())
arr

array([86.03331084, 37.7285648 , 48.64908087, 87.16563062, 38.40852563,
       37.20006318])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [27]:
#Code here
import numpy as np

def nth_largest(arr, n):
    # Validate input
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise ValueError("First argument must be a 1D numpy array.")
    if not isinstance(n, int) or n <= 0 or n > len(arr):
        raise ValueError("Second argument must be an integer in range 1 to len(arr).")

    # Use np.partition for efficient partial sorting
    return np.sort(arr)[-n]

arr1 = np.array([12, 34, 40, 7, 1, 0])
print(nth_largest(arr1, 3))  # Output: 12

arr2 = np.array([12, 34, 40, 7, 1, 0])
print(nth_largest(arr2, 1))  # Output: 40



12
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [29]:
#code here
a = np.array([1,2,3])
part1 = np.repeat(a,3)

part2 = np.tile(a,3)

res = np.concatenate((part1,part2))

res

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])